controller_list:
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gripper_finger1_joint
  - name: manipulator
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - workbench_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint